---
title: "Stacking"
author: "Adam Howes"
date: "`r Sys.Date()`"
toc: true
number-sections: true
format: 
  html: 
    code-fold: false
    html-math-method: katex
---

* Ideally you wouldn't need to do Bayesian model combination, just extend the model to have separate models as special cases
* However...

```{r}
library(loo)
library(rstanarm)
library(tidyverse)
```

```{r}
data(milk)

d <- milk |>
  tidyr::drop_na() |>
  mutate(neocortex = neocortex.perc / 100)

ggplot(d, aes(x = species, y = neocortex)) +
  geom_point() +
  coord_flip() +
  labs(y = "Fraction of brain neocortex", x = "Species") +
  theme_minimal()

fit1 <- stan_glm(kcal.per.g ~ 1, data = d, seed = 2030)
fit2 <- update(fit1, formula = kcal.per.g ~ neocortex)
fit3 <- update(fit1, formula = kcal.per.g ~ log(mass))
fit4 <- update(fit1, formula = kcal.per.g ~ neocortex + log(mass))

waic1 <- waic(fit1)
waic2 <- waic(fit2)
waic3 <- waic(fit3)
waic4 <- waic(fit4)

waics <- c(
  waic1$estimates["elpd_waic", 1],
  waic2$estimates["elpd_waic", 1],
  waic3$estimates["elpd_waic", 1],
  waic4$estimates["elpd_waic", 1]
)

waics

loo1 <- loo(fit1)
loo2 <- loo(fit2)
loo3 <- loo(fit3)
loo4 <- loo(fit4)

lpd_point <- cbind(
  loo1$pointwise[, "elpd_loo"], 
  loo2$pointwise[, "elpd_loo"],
  loo3$pointwise[, "elpd_loo"], 
  loo4$pointwise[, "elpd_loo"]
)

print(loo4)
```