---
title: "Advanced Stan"
author: "Adam Howes"
date: "`r Sys.Date()`"
toc: true
number-sections: true
format: 
  html: 
    code-fold: false
    html-math-method: katex
---

# Distributions

* Always specify bounds on parameters which have them

# Centered versus non-centered parameterisation

# Precomputation

* Calculate once rather than at every Stan iteration: move from the `model` or `transformed parameters` block into the `transformed data` block

# Vectorisation

* Replace for loops with matrix operations
* Note: what is the definition of "vectorised"? Doesn't apply to each element individually?

# Within-chain parallelisation

* You automatically get between-chain parallelisation in Stan
* It also supports within-chain parallelisation using [`reduce_sum`](https://mc-stan.org/docs/stan-users-guide/reduce-sum.html)
* Of course there is an overhead to parallelisation, so you have to think carefully about it

# Diagnostics

* Recommended to use rank histogram plots over traceplots

# Computing environment

```{r}
sessionInfo()
```