---
title: "`R-INLA` Poisson GLM predictions"
author: "Adam Howes"
date: "`r Sys.Date()`"
toc: true
number-sections: true
format: 
  html: 
    code-fold: false
    html-math-method: katex
---

# Poisson GLM

```{r}
#| message: false
#| warning: false

library(INLA)
library(ggplot2)

n <- 100
x <- runif(n)
eta <- -1 + x
lambda <- exp(eta)
y <- rpois(n, lambda)

df <- data.frame(id = 1:n, x = x, y = y)

ggplot(df, aes(x = id, y = y)) +
  geom_point() +
  theme_minimal()

fit <- INLA::inla(
  y ~ 1 + x,
  family = "poisson",
  data = data.frame(x, y), 
  control.predictor = list(link = 1),
  control.compute=list(config = TRUE)
)

summary(fit)

samples <- INLA::inla.posterior.sample(25, fit)

samples[[1]]$hyperpar
head(samples[[1]]$latent)
samples[[1]]$logdens

target <- paste0("Predictor:", 1:n)
predictor_samples <- sapply(samples, function(x) x$latent[target, 1])
lambda_samples <- exp(predictor_samples)

samples_df <- data.frame(lambda_samples) |>
  tibble::rowid_to_column("id") |>
  tidyr::pivot_longer(cols = starts_with("X"), names_to = "sample", values_to = "value") |>
  dplyr::mutate(sample = as.numeric(sub("^X", "", sample)))

head(samples_df)
dim(samples_df)

ggplot(samples_df, aes(x = id, y = value)) +
  geom_point() +
  labs(x = "id", y = "lambda") +
  theme_minimal()
```

# Adding zero inflation

```{r}
n <- 100
x <- runif(n)
eta <- -1 + x
lambda <- exp(eta)
p <- 0.35
z <- runif(n) > p
y <- rpois(n, lambda)
y[!z] <- 0

df <- data.frame(id = 1:n, x = x, y = y)

ggplot(df, aes(x = id, y = y)) +
  geom_point() +
  theme_minimal()

fit_zip <- INLA::inla(
  y ~ 1 + x,
  family = "zeroinflatedpoisson1",
  data = data.frame(x, y), 
  control.predictor = list(link = 1),
  control.compute=list(config = TRUE)
)

summary(fit_zip)

samples_zip <- INLA::inla.posterior.sample(25, fit_zip)

samples_zip[[1]]$hyperpar
head(samples_zip[[1]]$latent)
samples_zip[[1]]$logdens

target <- paste0("Predictor:", 1:n)

y_samples <- sapply(samples_zip, function(x) {
  predictor_sample <- x$latent[target, 1]
  lambda_sample <- exp(predictor_sample)
  stopifnot(length(lambda_sample) == n)
  y_sample <- rpois(n, lambda_sample)
  p_sample <- x$hyperpar
  z <- runif(n) > p_sample
  y[!z] <- 0
  return(y)
})

head(t(y_samples))

y_samples_df <- data.frame(y_samples) |>
  tibble::rowid_to_column("id") |>
  tidyr::pivot_longer(cols = starts_with("X"), names_to = "sample", values_to = "value") |>
  dplyr::mutate(sample = as.numeric(sub("^X", "", sample)))

y_samples_df |>
  dplyr::filter(sample == 1) |>
  ggplot(aes(x = id, y = value)) + 
    geom_point() +
    labs(title = "One sample from zero-inflated outcomes") +
    theme_minimal()
```

# Computing environment

```{r}
sessionInfo()
```